# Generated by Django 4.1.5 on 2023-06-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpermission',
            table=None,
        ),
    ]
