# Generated by Django 4.1.5 on 2023-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0004_customuser_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='generated_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
