# Generated by Django 4.1.5 on 2023-06-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0005_alter_customuser_generated_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='generated_key',
            new_name='generate_key',
        ),
    ]
