# Generated by Django 4.1.5 on 2023-06-14 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0006_rename_generated_key_customuser_generate_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
