# Generated by Django 4.1.5 on 2023-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0007_uploadedfile_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
