# Generated by Django 4.1.5 on 2023-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0009_alter_uploadedfile_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_field', models.CharField(max_length=100)),
                ('password_field', models.CharField(max_length=100)),
            ],
        ),
    ]
