# Generated by Django 4.1.5 on 2023-11-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0011_billing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={},
        ),
    ]
