# Generated by Django 4.1.5 on 2023-11-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0012_alter_billing_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
