# Generated by Django 4.1.5 on 2023-12-12 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0013_delete_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
