# Generated by Django 4.1.5 on 2023-12-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0014_usercredentials_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='user',
        ),
    ]
