# Generated by Django 4.1.5 on 2023-12-30 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smanage', '0015_remove_usercredentials_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='generate_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='key_field',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='password_field',
            field=models.CharField(max_length=255),
        ),
    ]
